name: Health check

# on:
#   schedule:
#     - cron: 40 14 * * *

jobs:
  health_check:
    runs-on: ubuntu-18.04
    steps:
      - uses: jtalk/url-health-check-action@v1.5
        with: 
          url: https://fullstackopen-pokedex.herokuapp.com/